name: Link Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args: --verbose --no-progress --timeout 30s ./  # Specify the directory or files to check
