name: Test JavaScript Output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-js-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Node.js version

      - name: Run hello-world.js and check output
        run: |
          output=$(node hello-world.js)
          if [ "$output" = "hello world" ]; then
            echo "Test passed!"
          else
            echo "Test failed: expected 'hello world' but got '$output'"
            exit 1
          fi

          name: Test JavaScript Output

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
